name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install backend dependencies
      working-directory: ./advanced-combo-project/backend
      run: npm install

    - name: Run backend tests
      working-directory: ./advanced-combo-project/backend
      run: npm test

    - name: Install frontend dependencies
      working-directory: ./advanced-combo-project/frontend
      run: npm install

    - name: Run frontend tests
      working-directory: ./advanced-combo-project/frontend
      run: npm test
